config/routes.rb
Rails.application.routes.draw do
  get 'page/home'

  get 'page/about'

  resources :cats

  root 'page#home'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
end


# == Schema Information
#
# Table name: cats
#
#  id         :integer          not null, primary key
#  imagefile  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:imagefile)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    @cats = Cat.all

    @catify = []

      @cats.sample(1).each do |cat|
        @catify.push(cat) #pushes 3 cat objects into this instance array
      end #do


  end #def

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/cats/_form.html.erb
<%= form_for(@cat) do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= image_tag @cat.imagefile %><br/>
    <%= f.label :imagefile %><br>
    <%= f.text_field :imagefile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<div class="editwrapper">
  <h1>Editing <%= @cat.imagefile %></h1>

  <%= render 'form' %>

  <%= link_to 'Show', @cat %> |
  <%= link_to 'Back', cats_path %>
</div><!--editwrapper-->

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Look at these cats!</h1>

<table class="table">
  <thead>
    <tr>
      <th>Cats!</th>
      <th>File Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= image_tag cat.imagefile, class: "indexcat" %></td>
        <td><%= cat.imagefile %></td>
        <td><%= link_to 'Edit Cat', edit_cat_path(cat) %></td>
        <td><%= link_to 'Delete Cat', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form' %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Imagefile:</strong>
  <%= @cat.imagefile %>
</p>

<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Cat Meme Me</title>

  <!--Google Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Amatic+SC:400,700' rel='stylesheet' type='text/css'>

  <!--Boostrap-->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/flatly/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
  <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>


  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Cats", cats_url %></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>
    <div class="container">

    <%= yield %>

    </div><!--container-->
  </div>
</body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/home.html.erb
<div class="row">
  <div class="introtxt">
    <h1>CatMemeMe!</h1>
    <center><p>Upload an Image [form field]</p></center>
    <center><%= button_to "CatMeme Me!", page_home_path, :class => "btn btn-primary", :method => :get %></center>
  </div><!--introtxt-->
</div><!--row-->

<div class="row">

  <div class="catframe">
    <div class="imgholder">

      <div class="cat-img-draggable">
          <%= image_tag @catify[0].imagefile, class: "cat-img-resizable" %>
      </div>

      <img class="uploaded-img" src="http://www.hawtcelebs.com/wp-content/uploads/2015/05/http-forum.phun.org-showthread.php-t-1482055-s-274379d94a598c3565561644c334147a_2.jpg">

    </div><!--imgholder-->
  </div><!--catframe-->
</div><!--row-->

<br><br>

<div class="row">



  <center><p>Share [not working]</p></center>
</div><!--row-->

<script type="text/javascript">
  $(document).ready(function() {
    $( ".cat-img-draggable" ).draggable({ containment: ".uploaded-img" });
    $( ".cat-img-resizable" ).resizable();
  });
</script>